# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Kubernetes Setup'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production

    env:
        TF_VAR_template_vm_id: ${{ secrets.TF_VAR_template_vm_id }}
        TF_VAR_number_of_control_planes: ${{ secrets.TF_VAR_number_of_control_planes }}
        TF_VAR_number_of_large_workers: ${{ secrets.TF_VAR_number_of_large_workers }}
        TF_VAR_number_of_medium_workers: ${{ secrets.TF_VAR_number_of_medium_workers }}
        TF_VAR_number_of_small_workers: ${{ secrets.TF_VAR_number_of_small_workers }}
        
        TF_VAR_node_name: ${{ secrets.TF_VAR_node_name }}
        TF_VAR_vlan_id: ${{ secrets.TF_VAR_vlan_id }}
        
        TF_VAR_provider_endpoint: ${{ secrets.TF_VAR_provider_endpoint }}
        TF_VAR_provider_username: ${{ secrets.TF_VAR_provider_username }}
        TF_VAR_provider_password: ${{ secrets.TF_VAR_provider_password }}
        
        TF_VAR_vm_password: ${{ secrets.TF_VAR_vm_password }}
        TF_VAR_vm_username: ${{ secrets.TF_VAR_vm_username }}
        TF_VAR_vm_public_key: ${{ secrets.TF_VAR_vm_public_key }}
        
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: "kubernetes/terraform"

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
        
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      shell: bash
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      shell: bash
      run: terraform plan -input=false

      # On changes to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve -input=false

  inventory:
    needs: terraform
    name: 'Copy Inventory'
    runs-on: self-hosted
    environment: production
    
    defaults:
      run:
        shell: bash
    steps:
    - name: Copy Inventory File
      run: cp -f /home/spainfra/terraform_state/kubernetes_cluster/inventory.ini ./kubernetes/kubespray/inventory/

  kubespray:
    needs: inventory
    name: 'Kubespray'
    runs-on: self-hosted
    container: 
        image: quay.io/kubespray/kubespray:v2.23.1
        volumes:
        - ./kubernetes/kubespray/inventory:/inventory
        - /home/spainfra/.ssh/id_rsa:/root/.ssh/id_rsa
        options: --user root
    defaults:
      run:
        working-directory: /kubespray/
    steps:
    - name: Folder
      run: pwd
    - name: Deploy Kubernetes
      run: ls
    - name: Deploy Kubernetes
      run: ls /inventory/
    - name: Deploy Kubernetes
      run: ls /kubespray/
    - name: Deploy Kubernetes
      run: whoami
    - name: Deploy Kubernetes
      run: ansible-playbook -i /inventory/inventory.ini --private-key /root/.ssh/id_rsa cluster.yml -become --become-user=root